using System.Text.Json.Serialization;

namespace CamusDB.Client;

[JsonSourceGenerationOptions]
[JsonSerializable(typeof(ColumnValue))]
[JsonSerializable(typeof(CamusResultSet))]
[JsonSerializable(typeof(CamusErrorResponse))]
[JsonSerializable(typeof(CamusCreateDatabaseRequest))]
[JsonSerializable(typeof(CamusCreateDatabaseResponse))]
[JsonSerializable(typeof(CamusCreateBranchDatabaseRequest))]
[JsonSerializable(typeof(CamusCreateBranchDatabaseResponse))]
[JsonSerializable(typeof(CamusDropDatabaseRequest))]
[JsonSerializable(typeof(CamusDropDatabaseResponse))]
[JsonSerializable(typeof(CamusExecuteDDLRequest))]
[JsonSerializable(typeof(CamusExecuteDDLResponse))]
[JsonSerializable(typeof(CamusExecuteSqlNonQueryRequest))]
[JsonSerializable(typeof(CamusExecuteSqlNonQueryResponse))]
[JsonSerializable(typeof(CamusExecuteSqlQueryRequest))]
[JsonSerializable(typeof(CamusExecuteSqlQueryResponse))]
[JsonSerializable(typeof(CamusHlcTimestamp))]
[JsonSerializable(typeof(CamusInsertRequest))]
[JsonSerializable(typeof(CamusStartTransactionRequest))]
[JsonSerializable(typeof(CamusStartTransactionResponse))]
[JsonSerializable(typeof(CamusTransactionRequest))]
[JsonSerializable(typeof(CamusBranchRow))]
[JsonSerializable(typeof(CamusShowBranchesRequest))]
[JsonSerializable(typeof(CamusShowBranchesResponse))]
[JsonSerializable(typeof(CamusShowAncestorsRequest))]
[JsonSerializable(typeof(CamusShowAncestorsResponse))]
internal sealed partial class CamusJsonSerializerContext : JsonSerializerContext;
